/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicMagicLinkVerifyRouteImport } from './routes/api/public/magic-link.verify'
import { Route as ApiPublicMagicLinkSendRouteImport } from './routes/api/public/magic-link.send'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicMagicLinkVerifyRoute =
  ApiPublicMagicLinkVerifyRouteImport.update({
    id: '/api/public/magic-link/verify',
    path: '/api/public/magic-link/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMagicLinkSendRoute = ApiPublicMagicLinkSendRouteImport.update({
  id: '/api/public/magic-link/send',
  path: '/api/public/magic-link/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/magic-link/send': typeof ApiPublicMagicLinkSendRoute
  '/api/public/magic-link/verify': typeof ApiPublicMagicLinkVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/magic-link/send': typeof ApiPublicMagicLinkSendRoute
  '/api/public/magic-link/verify': typeof ApiPublicMagicLinkVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/public/magic-link/send': typeof ApiPublicMagicLinkSendRoute
  '/api/public/magic-link/verify': typeof ApiPublicMagicLinkVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/join'
    | '/pricing'
    | '/projects'
    | '/services'
    | '/sponsors'
    | '/team'
    | '/blog/$slug'
    | '/api/public/magic-link/send'
    | '/api/public/magic-link/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/join'
    | '/pricing'
    | '/projects'
    | '/services'
    | '/sponsors'
    | '/team'
    | '/blog/$slug'
    | '/api/public/magic-link/send'
    | '/api/public/magic-link/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/join'
    | '/pricing'
    | '/projects'
    | '/services'
    | '/sponsors'
    | '/team'
    | '/blog/$slug'
    | '/api/public/magic-link/send'
    | '/api/public/magic-link/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  JoinRoute: typeof JoinRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SponsorsRoute: typeof SponsorsRoute
  TeamRoute: typeof TeamRoute
  ApiPublicMagicLinkSendRoute: typeof ApiPublicMagicLinkSendRoute
  ApiPublicMagicLinkVerifyRoute: typeof ApiPublicMagicLinkVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/magic-link/verify': {
      id: '/api/public/magic-link/verify'
      path: '/api/public/magic-link/verify'
      fullPath: '/api/public/magic-link/verify'
      preLoaderRoute: typeof ApiPublicMagicLinkVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/magic-link/send': {
      id: '/api/public/magic-link/send'
      path: '/api/public/magic-link/send'
      fullPath: '/api/public/magic-link/send'
      preLoaderRoute: typeof ApiPublicMagicLinkSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  JoinRoute: JoinRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SponsorsRoute: SponsorsRoute,
  TeamRoute: TeamRoute,
  ApiPublicMagicLinkSendRoute: ApiPublicMagicLinkSendRoute,
  ApiPublicMagicLinkVerifyRoute: ApiPublicMagicLinkVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
