// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createNullClient(): ReturnType<typeof createClient<Database>> {
  const noop = () => noop as any;
  const chain: any = new Proxy({}, {
    get: (_, prop) => {
      if (prop === 'then') return undefined;
      if (prop === 'eq' || prop === 'order' || prop === 'select' || prop === 'insert'
        || prop === 'update' || prop === 'delete' || prop === 'limit' || prop === 'single') {
        return () => chain;
      }
      if (prop === Symbol.toPrimitive) return undefined;
      return () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } });
    }
  });
  return {
    from: (_: string) => chain,
    auth: { getSession: () => Promise.resolve({ data: { session: null }, error: null }) },
    channel: () => ({ subscribe: () => {}, unsubscribe: noop }),
  } as any;
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('[Supabase] Environment variables not set — running with fallback content only.');
    return createNullClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase as object, prop, receiver);
  },
});
